local set = vim.opt
set.termguicolors = true
set.tabstop = 4
set.softtabstop = 4
set.shiftwidth = 4
set.expandtab = true
set.smarttab = true
set.autoindent = true
set.incsearch = true
set.ignorecase = true
set.smartcase = true
set.hlsearch = true
set.wildmode = {'longest', 'list', 'full'}
set.wildmenu = true
set.ruler = true
set.laststatus = 2
set.showcmd = true
set.showmode = true
set.list = true
set.listchars = {
  eol = '⤶',
  trail = '❤',
  extends = '◀',
  precedes = '▶',
}
set.wrap = true
set.breakindent = true
set.encoding = 'utf-8'
vim.scriptencoding = 'utf-8'
set.textwidth = 0
set.hidden = true
set.number = true
set.relativenumber = true
set.title = true
