return {
  { "Raimondi/delimitMate" },
  { "tiagovla/scope.nvim" },
  { "arkav/lualine-lsp-progress" },
  { "sindrets/diffview.nvim" },
  { "j-hui/fidget.nvim" },
  { "tpope/vim-scriptease" },
  { "voldikss/vim-floaterm" },
  { "chrisbra/unicode.vim" },
  { "tpope/vim-commentary" },
  { "neomake/neomake" },
  { "sbdchd/neoformat" },
  { "madox2/vim-ai" },
  { "Bilal2453/luvit-meta", lazy = true },
  { "averms/black-nvim" },
  { "dyng/ctrlsf.vim" },
  { "skywind3000/asyncrun.vim" },
  { "machakann/vim-sandwich" },
  { "wellle/targets.vim" },
  { "Vimjas/vim-python-pep8-indent", ft = { "python" } },
  { "jeetsukumaran/vim-pythonsense", ft = { "python" } },
  { "machakann/vim-swap", event = "VeryLazy" },
  { "tmux-plugins/vim-tmux", ft = { "tmux" } },
  { "cespare/vim-toml", ft = { "toml" }, branch = "main" },
}
