return {
  { "j-hui/fidget.nvim" },
  { "tpope/vim-scriptease" },
  { "voldikss/vim-floaterm" },
  { "chrisbra/unicode.vim" },
  { "tpope/vim-commentary" },
  { "neomake/neomake" },
  { "sbdchd/neoformat" },
  { "madox2/vim-ai" },
  { "averms/black-nvim" },
  { "dyng/ctrlsf.vim" },
  { "skywind3000/asyncrun.vim" },
  { "machakann/vim-sandwich" },
  { "wellle/targets.vim" },
}
